meta:
  schema_version: '2.0'
  system: Projects (views)
  system_id: SYS-projects-(views)
entities:
  components:
  - id: COMP-15
    name: Csrf
    files:
    - projects/django/django/views/csrf.py
    - projects/django/django/views/decorators/csrf.py
    - projects/django/django/views/decorators/gzip.py
    - projects/django/django/views/generic/base.py
  - id: COMP-16
    name: Debug
    files:
    - projects/django/django/views/debug.py
    - projects/django/django/views/decorators/debug.py
  - id: COMP-17
    name: Cache
    files:
    - projects/django/django/views/decorators/cache.py
  - id: COMP-18
    name: Clickjacking
    files:
    - projects/django/django/views/decorators/clickjacking.py
  - id: COMP-19
    name: Csp
    files:
    - projects/django/django/views/decorators/csp.py
  - id: COMP-20
    name: Http
    files:
    - projects/django/django/views/decorators/http.py
  - id: COMP-21
    name: Vary
    files:
    - projects/django/django/views/decorators/vary.py
  - id: COMP-22
    name: Defaults
    files:
    - projects/django/django/views/defaults.py
  - id: COMP-23
    name: Dates
    files:
    - projects/django/django/views/generic/dates.py
  - id: COMP-24
    name: Detail
    files:
    - projects/django/django/views/generic/detail.py
  - id: COMP-25
    name: Edit
    files:
    - projects/django/django/views/generic/edit.py
  - id: COMP-26
    name: List
    files:
    - projects/django/django/views/generic/list.py
  - id: COMP-27
    name: I18N
    files:
    - projects/django/django/views/i18n.py
  - id: COMP-28
    name: Static
    files:
    - projects/django/django/views/static.py
  - id: COMP-29
    name: Infrastructure
    files:
    - projects/django/django/views/decorators/common.py
  capabilities:
  - id: CAP-1
    name: Root Management
  - id: CAP-2
    name: Bookmarklet Management
  - id: CAP-3
    name: Tag Management
  - id: CAP-4
    name: Filter Management
  - id: CAP-5
    name: View Management
  - id: CAP-6
    name: Model Management
  - id: CAP-7
    name: ^Model Management
  - id: CAP-8
    name: Template Management
  - id: CAP-9
    name: Login Management
  - id: CAP-10
    name: Logout Management
  - id: CAP-11
    name: Password Change Management
  - id: CAP-12
    name: Password Reset Management
  - id: CAP-13
    name: Reset Management
  - id: CAP-14
    name: <Path:Url> Management
  - id: CAP-15
    name: Csrf
  - id: CAP-16
    name: Debug
  - id: CAP-17
    name: Cache
  - id: CAP-18
    name: Clickjacking
  - id: CAP-19
    name: Csp
  - id: CAP-20
    name: Http
  - id: CAP-21
    name: Vary
  - id: CAP-22
    name: Defaults
  - id: CAP-23
    name: Dates
  - id: CAP-24
    name: Detail
  - id: CAP-25
    name: Edit
  - id: CAP-26
    name: List
  - id: CAP-27
    name: I18N
  - id: CAP-28
    name: Static
  behaviors:
  - id: BEH-1
    name: 'GET '
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-2
    name: GET bookmarklets/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-3
    name: GET tags/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-4
    name: GET filters/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-5
    name: GET views/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-6
    name: GET views/<view>/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-7
    name: GET models/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-8
    name: GET ^models/(?P<app_label>[^.]+)\.(?P<model_name>[^/]+)/$
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-9
    name: GET templates/<path:template>/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-10
    name: GET login/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-11
    name: GET logout/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-12
    name: GET password_change/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-13
    name: GET password_change/done/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-14
    name: GET password_reset/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-15
    name: GET password_reset/done/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-16
    name: GET reset/<uidb64>/<token>/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-17
    name: GET reset/done/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-18
    name: GET <path:url>
    behavior_type: route_handler
    steps:
    - flatpage
    actor_id: ACT-1
  - id: BEH-19
    name: TemplateView
    behavior_type: use_case
    steps:
    - get
    actor_id: ACT-1
  - id: BEH-20
    name: RedirectView
    behavior_type: use_case
    steps:
    - get_redirect_url
    - get
    - head
    - post
    - options
    - delete
    - put
    - patch
    actor_id: ACT-1
  - id: BEH-21
    name: BaseDateListView
    behavior_type: use_case
    steps:
    - get
    - get_dated_items
    - get_ordering
    - get_dated_queryset
    - get_date_list_period
    - get_date_list
    actor_id: ACT-1
  - id: BEH-22
    name: BaseArchiveIndexView
    behavior_type: use_case
    steps:
    - get_dated_items
    actor_id: ACT-1
  - id: BEH-23
    name: BaseYearArchiveView
    behavior_type: use_case
    steps:
    - get_dated_items
    - get_make_object_list
    actor_id: ACT-1
  - id: BEH-24
    name: BaseMonthArchiveView
    behavior_type: use_case
    steps:
    - get_dated_items
    actor_id: ACT-1
  - id: BEH-25
    name: BaseWeekArchiveView
    behavior_type: use_case
    steps:
    - get_dated_items
    actor_id: ACT-1
  - id: BEH-26
    name: BaseDayArchiveView
    behavior_type: use_case
    steps:
    - get_dated_items
    actor_id: ACT-1
  - id: BEH-27
    name: BaseTodayArchiveView
    behavior_type: use_case
    steps:
    - get_dated_items
    actor_id: ACT-1
  - id: BEH-28
    name: BaseDateDetailView
    behavior_type: use_case
    steps:
    - get_object
    actor_id: ACT-1
  - id: BEH-29
    name: BaseDetailView
    behavior_type: use_case
    steps:
    - get
    actor_id: ACT-1
  - id: BEH-30
    name: ProcessFormView
    behavior_type: use_case
    steps:
    - get
    - post
    - put
    actor_id: ACT-1
  - id: BEH-31
    name: BaseCreateView
    behavior_type: use_case
    steps:
    - get
    - post
    actor_id: ACT-1
  - id: BEH-32
    name: BaseUpdateView
    behavior_type: use_case
    steps:
    - get
    - post
    actor_id: ACT-1
  - id: BEH-33
    name: BaseDeleteView
    behavior_type: use_case
    steps:
    - post
    - form_valid
    actor_id: ACT-1
  - id: BEH-34
    name: BaseListView
    behavior_type: use_case
    steps:
    - get
    actor_id: ACT-1
  - id: BEH-35
    name: JavaScriptCatalog
    behavior_type: use_case
    steps:
    - get
    - get_paths
    - get_plural
    - get_catalog
    - get_context_data
    - render_to_response
    actor_id: ACT-1
  actors:
  - id: ACT-1
    name: API Consumer
    actor_type: system
    evidence_source: routes
  layers:
  - id: LAYER-web
    name: web
  - id: LAYER-infra
    name: infra
relationships:
- from: COMP-15
  to: CAP-15
  type: realizes
- from: COMP-16
  to: CAP-16
  type: realizes
- from: COMP-17
  to: CAP-17
  type: realizes
- from: COMP-18
  to: CAP-18
  type: realizes
- from: COMP-19
  to: CAP-19
  type: realizes
- from: COMP-20
  to: CAP-20
  type: realizes
- from: COMP-21
  to: CAP-21
  type: realizes
- from: COMP-22
  to: CAP-22
  type: realizes
- from: COMP-23
  to: CAP-23
  type: realizes
- from: COMP-24
  to: CAP-24
  type: realizes
- from: COMP-25
  to: CAP-25
  type: realizes
- from: COMP-26
  to: CAP-26
  type: realizes
- from: COMP-27
  to: CAP-27
  type: realizes
- from: COMP-28
  to: CAP-28
  type: realizes
- from: COMP-15
  to: COMP-18
  type: depends-on
- from: COMP-20
  to: COMP-17
  type: depends-on
- from: COMP-26
  to: COMP-22
  type: depends-on
- from: COMP-16
  to: COMP-18
  type: depends-on
- from: COMP-16
  to: COMP-28
  type: depends-on
- from: COMP-22
  to: COMP-15
  type: depends-on
- from: COMP-24
  to: COMP-26
  type: depends-on
- from: COMP-15
  to: COMP-21
  type: depends-on
- from: COMP-23
  to: COMP-25
  type: depends-on
- from: COMP-27
  to: COMP-26
  type: depends-on
- from: COMP-16
  to: COMP-21
  type: depends-on
- from: COMP-20
  to: COMP-16
  type: depends-on
- from: COMP-23
  to: COMP-27
  type: depends-on
- from: COMP-20
  to: COMP-15
  type: depends-on
- from: COMP-24
  to: COMP-25
  type: depends-on
- from: COMP-27
  to: COMP-25
  type: depends-on
- from: COMP-26
  to: COMP-25
  type: depends-on
- from: COMP-23
  to: COMP-24
  type: depends-on
- from: COMP-23
  to: COMP-22
  type: depends-on
- from: COMP-24
  to: COMP-27
  type: depends-on
- from: COMP-25
  to: COMP-20
  type: depends-on
- from: COMP-22
  to: COMP-19
  type: depends-on
- from: COMP-26
  to: COMP-27
  type: depends-on
- from: COMP-25
  to: COMP-16
  type: depends-on
- from: COMP-16
  to: COMP-17
  type: depends-on
- from: COMP-22
  to: COMP-16
  type: depends-on
- from: COMP-27
  to: COMP-24
  type: depends-on
- from: COMP-16
  to: COMP-20
  type: depends-on
- from: COMP-25
  to: COMP-15
  type: depends-on
- from: COMP-25
  to: COMP-23
  type: depends-on
- from: COMP-24
  to: COMP-22
  type: depends-on
- from: COMP-20
  to: COMP-19
  type: depends-on
- from: COMP-27
  to: COMP-22
  type: depends-on
- from: COMP-16
  to: COMP-15
  type: depends-on
- from: COMP-22
  to: COMP-29
  type: depends-on
- from: COMP-27
  to: COMP-28
  type: depends-on
- from: COMP-26
  to: COMP-28
  type: depends-on
- from: COMP-20
  to: COMP-29
  type: depends-on
- from: COMP-17
  to: COMP-20
  type: depends-on
- from: COMP-15
  to: COMP-17
  type: depends-on
- from: COMP-17
  to: COMP-16
  type: depends-on
- from: COMP-16
  to: COMP-19
  type: depends-on
- from: COMP-15
  to: COMP-20
  type: depends-on
- from: COMP-17
  to: COMP-15
  type: depends-on
- from: COMP-15
  to: COMP-16
  type: depends-on
- from: COMP-22
  to: COMP-27
  type: depends-on
- from: COMP-23
  to: COMP-28
  type: depends-on
- from: COMP-25
  to: COMP-24
  type: depends-on
- from: COMP-25
  to: COMP-22
  type: depends-on
- from: COMP-23
  to: COMP-15
  type: depends-on
- from: COMP-25
  to: COMP-26
  type: depends-on
- from: COMP-26
  to: COMP-20
  type: depends-on
- from: COMP-24
  to: COMP-28
  type: depends-on
- from: COMP-16
  to: COMP-29
  type: depends-on
- from: COMP-16
  to: COMP-22
  type: depends-on
- from: COMP-26
  to: COMP-16
  type: depends-on
- from: COMP-24
  to: COMP-15
  type: depends-on
- from: COMP-17
  to: COMP-19
  type: depends-on
- from: COMP-27
  to: COMP-15
  type: depends-on
- from: COMP-26
  to: COMP-15
  type: depends-on
- from: COMP-26
  to: COMP-23
  type: depends-on
- from: COMP-27
  to: COMP-23
  type: depends-on
- from: COMP-22
  to: COMP-18
  type: depends-on
- from: COMP-22
  to: COMP-28
  type: depends-on
- from: COMP-15
  to: COMP-19
  type: depends-on
- from: COMP-22
  to: COMP-21
  type: depends-on
- from: COMP-28
  to: COMP-20
  type: depends-on
- from: COMP-25
  to: COMP-27
  type: depends-on
- from: COMP-21
  to: COMP-17
  type: depends-on
- from: COMP-23
  to: COMP-20
  type: depends-on
- from: COMP-20
  to: COMP-18
  type: depends-on
- from: COMP-23
  to: COMP-16
  type: depends-on
- from: COMP-20
  to: COMP-21
  type: depends-on
- from: COMP-16
  to: COMP-27
  type: depends-on
- from: COMP-17
  to: COMP-29
  type: depends-on
- from: COMP-24
  to: COMP-20
  type: depends-on
- from: COMP-27
  to: COMP-20
  type: depends-on
- from: COMP-15
  to: COMP-29
  type: depends-on
- from: COMP-24
  to: COMP-16
  type: depends-on
- from: COMP-27
  to: COMP-16
  type: depends-on
- from: COMP-22
  to: COMP-17
  type: depends-on
- from: COMP-23
  to: COMP-26
  type: depends-on
- from: COMP-24
  to: COMP-23
  type: depends-on
- from: COMP-22
  to: COMP-20
  type: depends-on
- from: COMP-17
  to: COMP-18
  type: depends-on
- from: COMP-25
  to: COMP-28
  type: depends-on
- from: COMP-17
  to: COMP-21
  type: depends-on
- from: COMP-26
  to: COMP-24
  type: depends-on
- from: LAYER-WEB
  to: COMP-15
  type: contains
- from: LAYER-WEB
  to: COMP-16
  type: contains
- from: LAYER-WEB
  to: COMP-17
  type: contains
- from: LAYER-WEB
  to: COMP-18
  type: contains
- from: LAYER-WEB
  to: COMP-19
  type: contains
- from: LAYER-WEB
  to: COMP-20
  type: contains
- from: LAYER-WEB
  to: COMP-21
  type: contains
- from: LAYER-WEB
  to: COMP-22
  type: contains
- from: LAYER-WEB
  to: COMP-23
  type: contains
- from: LAYER-WEB
  to: COMP-24
  type: contains
- from: LAYER-WEB
  to: COMP-25
  type: contains
- from: LAYER-WEB
  to: COMP-26
  type: contains
- from: LAYER-WEB
  to: COMP-27
  type: contains
- from: LAYER-WEB
  to: COMP-28
  type: contains
- from: LAYER-INFRA
  to: COMP-29
  type: contains
