flowchart LR
    subgraph ungrouped[ungrouped]
        COMP_1[Scanner]
        COMP_2[Body Hints]
        COMP_3[Test Analyzer]
        COMP_4[Generator]
        COMP_5[Blocks]
        COMP_6[Interfaces]
        COMP_7[Metrics]
        COMP_8[Recursive]
        COMP_9[Slicers]
        COMP_10[Display]
        COMP_11[Types]
    end
    COMP_4 -->|depends-on| COMP_1
    COMP_4 -->|depends-on| COMP_5
    COMP_4 -->|depends-on| COMP_6
    COMP_4 -->|depends-on| COMP_7
    COMP_1 -->|depends-on| COMP_11
    COMP_5 -->|depends-on| COMP_1
    COMP_5 -->|depends-on| COMP_11
    COMP_6 -->|depends-on| COMP_11
    COMP_7 -->|depends-on| COMP_11
    COMP_8 -->|depends-on| COMP_1
    COMP_8 -->|depends-on| COMP_6
    COMP_8 -->|depends-on| COMP_11
    COMP_9 -->|depends-on| COMP_11
