flowchart TB
    subgraph ungrouped[Components]
        COMP_ENRICH[enrich]
        COMP_DECOMPOSE[decompose]
        COMP_INIT[Package Init]
    end
    CAP_ENRICH(Model Enrichment)
    CAP_DECOMPOSE(Model Decomposition)
    CAP_WRITE("Sub-Model Persistence")
    COMP_ENRICH ==>|realizes| CAP_ENRICH
    COMP_DECOMPOSE ==>|realizes| CAP_DECOMPOSE
    COMP_DECOMPOSE ==>|realizes| CAP_WRITE
