meta:
  schema_version: '2.0'
  system: Observe Types
  system_id: SYS-observe-types
entities:
  capabilities:
  - id: CAP-1
    name: Observe Types
  - id: CAP-2
    name: Observe
  - id: CAP-3
    name: Context Gen
  - id: CAP-4
    name: Artifacts
  - id: CAP-5
    name: Emit
relationships: []
