flowchart LR
    subgraph ungrouped[ungrouped]
        COMP_FROM_CODE[from_code]
        COMP_CONSTRAINT_DETECTOR[constraint_detector]
        COMP_ROUTE_DETECTOR[route_detector]
    end
    COMP_FROM_CODE -->|depends-on| COMP_ROUTE_DETECTOR
    COMP_FROM_CODE -->|depends-on| COMP_CONSTRAINT_DETECTOR
    COMP_FROM_CODE -->|depends-on| ACT_CORE
    COMP_FROM_CODE -->|depends-on| ACT_CONFIG
    COMP_FROM_CODE -->|depends-on| ACT_MANIFEST
