meta:
  schema_version: '2.0'
  system: Src (extract)
  system_id: SYS-src-(extract)
entities:
  capabilities:
  - id: CAP-1
    name: Root Management
  - id: CAP-2
    name: Bookmarklet Management
  - id: CAP-3
    name: Tag Management
  - id: CAP-4
    name: Filter Management
  - id: CAP-5
    name: View Management
  - id: CAP-6
    name: Model Management
  - id: CAP-7
    name: ^Model Management
  - id: CAP-8
    name: Template Management
  - id: CAP-9
    name: Login Management
  - id: CAP-10
    name: Logout Management
  - id: CAP-11
    name: Password Change Management
  - id: CAP-12
    name: Password Reset Management
  - id: CAP-13
    name: Reset Management
  - id: CAP-14
    name: <Path:Url> Management
  - id: CAP-15
    name: Constraint Detector
  - id: CAP-16
    name: From Artifacts
  - id: CAP-17
    name: From Code
  - id: CAP-18
    name: Route Detector
  - id: CAP-19
    name: Table Parser
  behaviors:
  - id: BEH-1
    name: 'GET '
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-2
    name: GET bookmarklets/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-3
    name: GET tags/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-4
    name: GET filters/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-5
    name: GET views/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-6
    name: GET views/<view>/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-7
    name: GET models/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-8
    name: GET ^models/(?P<app_label>[^.]+)\.(?P<model_name>[^/]+)/$
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-9
    name: GET templates/<path:template>/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-12
    name: GET password_change/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-13
    name: GET password_change/done/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-14
    name: GET password_reset/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-15
    name: GET password_reset/done/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-10
    name: GET login/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-11
    name: GET logout/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-16
    name: GET reset/<uidb64>/<token>/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-17
    name: GET reset/done/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-18
    name: GET <path:url>
    behavior_type: route_handler
    steps:
    - flatpage
    actor_id: ACT-1
  actors:
  - id: ACT-1
    name: API Consumer
    actor_type: system
    evidence_source: routes
relationships: []
