meta:
  schema_version: '2.0'
  system: Monitoring (manifest)
  system_id: SYS-monitoring-(manifest)
entities:
  components:
  - id: COMP-1
    name: Interfaces
    files:
    - src/architecture_model/manifest/interfaces.py
  - id: COMP-2
    name: Metrics
    files:
    - src/architecture_model/manifest/metrics.py
  - id: COMP-3
    name: Scanner
    files:
    - src/architecture_model/manifest/scanner.py
  - id: COMP-4
    name: Slicers
    files:
    - src/architecture_model/manifest/slicers.py
  - id: COMP-5
    name: Multi Scanner
    files:
    - src/architecture_model/manifest/multi_scanner.py
  - id: COMP-6
    name: Scan Cache
    files:
    - src/architecture_model/manifest/scan_cache.py
  - id: COMP-7
    name: Kt Scanner
    files:
    - src/architecture_model/manifest/kt_scanner.py
  - id: COMP-8
    name: Generator
    files:
    - src/architecture_model/manifest/generator.py
  - id: COMP-9
    name: Blocks
    files:
    - src/architecture_model/manifest/blocks.py
  capabilities:
  - id: CAP-1
    name: Interfaces
  - id: CAP-2
    name: Metrics
  - id: CAP-3
    name: Scanner
  - id: CAP-4
    name: Slicers
  - id: CAP-5
    name: Multi Scanner
  - id: CAP-6
    name: Scan Cache
  - id: CAP-7
    name: Kt Scanner
  - id: CAP-8
    name: Generator
  - id: CAP-9
    name: Blocks
relationships:
- from: COMP-1
  to: CAP-1
  type: realizes
- from: COMP-2
  to: CAP-2
  type: realizes
- from: COMP-3
  to: CAP-7
  type: realizes
- from: COMP-4
  to: CAP-4
  type: realizes
- from: COMP-5
  to: CAP-5
  type: realizes
- from: COMP-6
  to: CAP-6
  type: realizes
- from: COMP-7
  to: CAP-7
  type: realizes
- from: COMP-8
  to: CAP-8
  type: realizes
- from: COMP-9
  to: CAP-9
  type: realizes
- from: COMP-1
  to: COMP-4
  type: depends-on
- from: COMP-9
  to: COMP-4
  type: depends-on
- from: COMP-8
  to: COMP-9
  type: depends-on
- from: COMP-1
  to: COMP-3
  type: depends-on
- from: COMP-1
  to: COMP-9
  type: depends-on
- from: COMP-1
  to: COMP-6
  type: depends-on
- from: COMP-9
  to: COMP-3
  type: depends-on
- from: COMP-1
  to: COMP-8
  type: depends-on
- from: COMP-9
  to: COMP-6
  type: depends-on
- from: COMP-1
  to: COMP-2
  type: depends-on
- from: COMP-9
  to: COMP-8
  type: depends-on
- from: COMP-9
  to: COMP-2
  type: depends-on
- from: COMP-2
  to: COMP-4
  type: depends-on
- from: COMP-6
  to: COMP-4
  type: depends-on
- from: COMP-1
  to: COMP-7
  type: depends-on
- from: COMP-9
  to: COMP-1
  type: depends-on
- from: COMP-2
  to: COMP-9
  type: depends-on
- from: COMP-6
  to: COMP-9
  type: depends-on
- from: COMP-6
  to: COMP-3
  type: depends-on
- from: COMP-8
  to: COMP-4
  type: depends-on
- from: COMP-9
  to: COMP-7
  type: depends-on
- from: COMP-4
  to: COMP-3
  type: depends-on
- from: COMP-4
  to: COMP-9
  type: depends-on
- from: COMP-1
  to: COMP-5
  type: depends-on
- from: COMP-2
  to: COMP-3
  type: depends-on
- from: COMP-2
  to: COMP-6
  type: depends-on
- from: COMP-4
  to: COMP-6
  type: depends-on
- from: COMP-4
  to: COMP-8
  type: depends-on
- from: COMP-2
  to: COMP-8
  type: depends-on
- from: COMP-4
  to: COMP-2
  type: depends-on
- from: COMP-4
  to: COMP-1
  type: depends-on
- from: COMP-6
  to: COMP-2
  type: depends-on
- from: COMP-2
  to: COMP-1
  type: depends-on
- from: COMP-6
  to: COMP-1
  type: depends-on
- from: COMP-6
  to: COMP-8
  type: depends-on
- from: COMP-4
  to: COMP-7
  type: depends-on
- from: COMP-7
  to: COMP-4
  type: depends-on
- from: COMP-2
  to: COMP-7
  type: depends-on
- from: COMP-6
  to: COMP-7
  type: depends-on
- from: COMP-7
  to: COMP-9
  type: depends-on
- from: COMP-2
  to: COMP-5
  type: depends-on
- from: COMP-6
  to: COMP-5
  type: depends-on
- from: COMP-8
  to: COMP-1
  type: depends-on
- from: COMP-7
  to: COMP-2
  type: depends-on
- from: COMP-7
  to: COMP-3
  type: depends-on
- from: COMP-4
  to: COMP-5
  type: depends-on
- from: COMP-7
  to: COMP-6
  type: depends-on
- from: COMP-8
  to: COMP-7
  type: depends-on
- from: COMP-7
  to: COMP-8
  type: depends-on
- from: COMP-7
  to: COMP-1
  type: depends-on
- from: COMP-8
  to: COMP-5
  type: depends-on
- from: COMP-8
  to: COMP-3
  type: depends-on
- from: COMP-8
  to: COMP-6
  type: depends-on
- from: COMP-3
  to: COMP-4
  type: depends-on
- from: COMP-7
  to: COMP-5
  type: depends-on
- from: COMP-3
  to: COMP-9
  type: depends-on
- from: COMP-9
  to: COMP-5
  type: depends-on
- from: COMP-3
  to: COMP-6
  type: depends-on
- from: COMP-3
  to: COMP-8
  type: depends-on
- from: COMP-3
  to: COMP-2
  type: depends-on
- from: COMP-5
  to: COMP-4
  type: depends-on
- from: COMP-3
  to: COMP-1
  type: depends-on
- from: COMP-5
  to: COMP-9
  type: depends-on
- from: COMP-3
  to: COMP-7
  type: depends-on
- from: COMP-5
  to: COMP-2
  type: depends-on
- from: COMP-5
  to: COMP-3
  type: depends-on
- from: COMP-5
  to: COMP-6
  type: depends-on
- from: COMP-8
  to: COMP-2
  type: depends-on
- from: COMP-3
  to: COMP-5
  type: depends-on
- from: COMP-5
  to: COMP-8
  type: depends-on
- from: COMP-5
  to: COMP-1
  type: depends-on
- from: COMP-5
  to: COMP-7
  type: depends-on
- from: LAYER-DATA
  to: COMP-1
  type: contains
- from: LAYER-DATA
  to: COMP-2
  type: contains
- from: LAYER-DATA
  to: COMP-3
  type: contains
- from: LAYER-DATA
  to: COMP-4
  type: contains
- from: LAYER-DATA
  to: COMP-5
  type: contains
- from: LAYER-DATA
  to: COMP-6
  type: contains
- from: LAYER-DATA
  to: COMP-7
  type: contains
- from: LAYER-DATA
  to: COMP-8
  type: contains
- from: LAYER-DATA
  to: COMP-9
  type: contains
