meta:
  schema_version: '2.0'
  system: Projects (middleware)
  system_id: SYS-projects-(middleware)
entities:
  components:
  - id: COMP-1
    name: Cache
    files:
    - projects/django/django/middleware/cache.py
  - id: COMP-2
    name: Clickjacking
    files:
    - projects/django/django/middleware/clickjacking.py
  - id: COMP-3
    name: Common
    files:
    - projects/django/django/middleware/common.py
  - id: COMP-4
    name: Csp
    files:
    - projects/django/django/middleware/csp.py
  - id: COMP-5
    name: Csrf
    files:
    - projects/django/django/middleware/csrf.py
  - id: COMP-6
    name: Gzip
    files:
    - projects/django/django/middleware/gzip.py
  - id: COMP-7
    name: Http
    files:
    - projects/django/django/middleware/http.py
  - id: COMP-8
    name: Locale
    files:
    - projects/django/django/middleware/locale.py
  - id: COMP-9
    name: Security
    files:
    - projects/django/django/middleware/security.py
  capabilities:
  - id: CAP-1
    name: Root Management
  - id: CAP-2
    name: Bookmarklet Management
  - id: CAP-3
    name: Tag Management
  - id: CAP-4
    name: Filter Management
  - id: CAP-5
    name: View Management
  - id: CAP-6
    name: Model Management
  - id: CAP-7
    name: ^Model Management
  - id: CAP-8
    name: Template Management
  - id: CAP-9
    name: Login Management
  - id: CAP-10
    name: Logout Management
  - id: CAP-11
    name: Password Change Management
  - id: CAP-12
    name: Password Reset Management
  - id: CAP-13
    name: Reset Management
  - id: CAP-14
    name: <Path:Url> Management
  - id: CAP-15
    name: Cache
  - id: CAP-16
    name: Clickjacking
  - id: CAP-17
    name: Csp
  - id: CAP-18
    name: Csrf
  - id: CAP-19
    name: Gzip
  - id: CAP-20
    name: Http
  - id: CAP-21
    name: Locale
  - id: CAP-22
    name: Security
  behaviors:
  - id: BEH-1
    name: 'GET '
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-2
    name: GET bookmarklets/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-3
    name: GET tags/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-4
    name: GET filters/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-5
    name: GET views/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-6
    name: GET views/<view>/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-7
    name: GET models/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-8
    name: GET ^models/(?P<app_label>[^.]+)\.(?P<model_name>[^/]+)/$
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-9
    name: GET templates/<path:template>/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-10
    name: GET login/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-11
    name: GET logout/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-12
    name: GET password_change/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-13
    name: GET password_change/done/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-14
    name: GET password_reset/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-15
    name: GET password_reset/done/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-16
    name: GET reset/<uidb64>/<token>/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-17
    name: GET reset/done/
    behavior_type: route_handler
    steps:
    - ''
    actor_id: ACT-1
  - id: BEH-18
    name: GET <path:url>
    behavior_type: route_handler
    steps:
    - flatpage
    actor_id: ACT-1
  - id: BEH-19
    name: CommonMiddleware middleware workflow
    behavior_type: workflow
    steps:
    - process_request
    - process_response
  - id: BEH-20
    name: ContentSecurityPolicyMiddleware middleware workflow
    behavior_type: workflow
    steps:
    - process_request
    - process_response
  - id: BEH-21
    name: CsrfViewMiddleware middleware workflow
    behavior_type: workflow
    steps:
    - process_request
    - process_view
    - process_response
  - id: BEH-22
    name: LocaleMiddleware middleware workflow
    behavior_type: workflow
    steps:
    - process_request
    - process_response
  - id: BEH-23
    name: SecurityMiddleware middleware workflow
    behavior_type: workflow
    steps:
    - process_request
    - process_response
  actors:
  - id: ACT-1
    name: API Consumer
    actor_type: system
    evidence_source: routes
  layers:
  - id: LAYER-infra
    name: infra
relationships:
- from: COMP-1
  to: CAP-15
  type: realizes
- from: COMP-2
  to: CAP-16
  type: realizes
- from: COMP-4
  to: CAP-17
  type: realizes
- from: COMP-5
  to: CAP-18
  type: realizes
- from: COMP-6
  to: CAP-19
  type: realizes
- from: COMP-7
  to: CAP-20
  type: realizes
- from: COMP-8
  to: CAP-21
  type: realizes
- from: COMP-9
  to: CAP-22
  type: realizes
- from: COMP-1
  to: COMP-9
  type: depends-on
- from: COMP-2
  to: COMP-5
  type: depends-on
- from: COMP-1
  to: COMP-4
  type: depends-on
- from: COMP-7
  to: COMP-8
  type: depends-on
- from: COMP-9
  to: COMP-1
  type: depends-on
- from: COMP-6
  to: COMP-7
  type: depends-on
- from: COMP-6
  to: COMP-4
  type: depends-on
- from: COMP-6
  to: COMP-9
  type: depends-on
- from: COMP-9
  to: COMP-5
  type: depends-on
- from: COMP-2
  to: COMP-7
  type: depends-on
- from: COMP-2
  to: COMP-4
  type: depends-on
- from: COMP-2
  to: COMP-9
  type: depends-on
- from: COMP-5
  to: COMP-3
  type: depends-on
- from: COMP-3
  to: COMP-6
  type: depends-on
- from: COMP-8
  to: COMP-3
  type: depends-on
- from: COMP-3
  to: COMP-2
  type: depends-on
- from: COMP-7
  to: COMP-1
  type: depends-on
- from: COMP-8
  to: COMP-6
  type: depends-on
- from: COMP-9
  to: COMP-7
  type: depends-on
- from: COMP-9
  to: COMP-4
  type: depends-on
- from: COMP-5
  to: COMP-6
  type: depends-on
- from: COMP-4
  to: COMP-3
  type: depends-on
- from: COMP-5
  to: COMP-2
  type: depends-on
- from: COMP-4
  to: COMP-6
  type: depends-on
- from: COMP-7
  to: COMP-5
  type: depends-on
- from: COMP-4
  to: COMP-2
  type: depends-on
- from: COMP-8
  to: COMP-2
  type: depends-on
- from: COMP-3
  to: COMP-8
  type: depends-on
- from: COMP-1
  to: COMP-3
  type: depends-on
- from: COMP-5
  to: COMP-8
  type: depends-on
- from: COMP-7
  to: COMP-9
  type: depends-on
- from: COMP-4
  to: COMP-8
  type: depends-on
- from: COMP-7
  to: COMP-4
  type: depends-on
- from: COMP-1
  to: COMP-6
  type: depends-on
- from: COMP-1
  to: COMP-2
  type: depends-on
- from: COMP-6
  to: COMP-3
  type: depends-on
- from: COMP-3
  to: COMP-1
  type: depends-on
- from: COMP-2
  to: COMP-3
  type: depends-on
- from: COMP-8
  to: COMP-1
  type: depends-on
- from: COMP-2
  to: COMP-6
  type: depends-on
- from: COMP-6
  to: COMP-2
  type: depends-on
- from: COMP-1
  to: COMP-8
  type: depends-on
- from: COMP-5
  to: COMP-1
  type: depends-on
- from: COMP-4
  to: COMP-1
  type: depends-on
- from: COMP-6
  to: COMP-8
  type: depends-on
- from: COMP-3
  to: COMP-5
  type: depends-on
- from: COMP-9
  to: COMP-3
  type: depends-on
- from: COMP-8
  to: COMP-5
  type: depends-on
- from: COMP-9
  to: COMP-6
  type: depends-on
- from: COMP-2
  to: COMP-8
  type: depends-on
- from: COMP-9
  to: COMP-2
  type: depends-on
- from: COMP-3
  to: COMP-9
  type: depends-on
- from: COMP-4
  to: COMP-5
  type: depends-on
- from: COMP-3
  to: COMP-7
  type: depends-on
- from: COMP-3
  to: COMP-4
  type: depends-on
- from: COMP-5
  to: COMP-7
  type: depends-on
- from: COMP-8
  to: COMP-7
  type: depends-on
- from: COMP-5
  to: COMP-9
  type: depends-on
- from: COMP-8
  to: COMP-4
  type: depends-on
- from: COMP-8
  to: COMP-9
  type: depends-on
- from: COMP-7
  to: COMP-3
  type: depends-on
- from: COMP-5
  to: COMP-4
  type: depends-on
- from: COMP-1
  to: COMP-5
  type: depends-on
- from: COMP-4
  to: COMP-7
  type: depends-on
- from: COMP-9
  to: COMP-8
  type: depends-on
- from: COMP-4
  to: COMP-9
  type: depends-on
- from: COMP-7
  to: COMP-6
  type: depends-on
- from: COMP-6
  to: COMP-1
  type: depends-on
- from: COMP-7
  to: COMP-2
  type: depends-on
- from: COMP-6
  to: COMP-5
  type: depends-on
- from: COMP-1
  to: COMP-7
  type: depends-on
- from: COMP-2
  to: COMP-1
  type: depends-on
- from: LAYER-INFRA
  to: COMP-1
  type: contains
- from: LAYER-INFRA
  to: COMP-2
  type: contains
- from: LAYER-INFRA
  to: COMP-3
  type: contains
- from: LAYER-INFRA
  to: COMP-4
  type: contains
- from: LAYER-INFRA
  to: COMP-5
  type: contains
- from: LAYER-INFRA
  to: COMP-6
  type: contains
- from: LAYER-INFRA
  to: COMP-7
  type: contains
- from: LAYER-INFRA
  to: COMP-8
  type: contains
- from: LAYER-INFRA
  to: COMP-9
  type: contains
