"""Configuration loader for the Architecture Model Standard.

Loads project configuration from .architecture-model.yaml or auto-discovers
project structure when no config file exists. Includes full auto-generation
of functional blocks from directory structure and import analysis.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from .schema import (
    ProjectConfig,
    OutputConfig,
    LayerConfig,
    FunctionalBlockConfig,
    MetricConfig,
)


CONFIG_FILENAME = ".architecture-model.yaml"


def load_config(root: Path) -> ProjectConfig:
    """Load project configuration from .architecture-model.yaml.

    Args:
        root: Project root directory containing the config file.

    Returns:
        ProjectConfig loaded from file.

    Raises:
        FileNotFoundError: If config file doesn't exist.
    """
    config_path = root / CONFIG_FILENAME
    if not config_path.exists():
        raise FileNotFoundError(
            f"No {CONFIG_FILENAME} found in {root}. "
            f"Run `architecture-model init` to generate one, or use get_config() for auto-discovery."
        )

    data = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    if not data:
        data = {}

    return ProjectConfig.from_dict(data, root=root)


def discover_config(root: Path) -> ProjectConfig:
    """Auto-discover project configuration by scanning filesystem.

    Inspects the directory structure to infer layers, functional blocks,
    and metrics without requiring a config file. Produces a complete,
    usable configuration including auto-generated F-blocks.

    Args:
        root: Project root directory to scan.

    Returns:
        ProjectConfig with auto-discovered values.
    """
    name = root.name

    # Discover layers from common directory patterns
    layers = _discover_layers(root)

    # Discover metrics from what directories exist
    metrics = _discover_metrics(root)

    # Auto-discover functional blocks from source structure
    functional_blocks = _discover_functional_blocks(root)

    # If no layers found from heuristics but we found F-blocks,
    # derive layers from the F-block directories
    if not layers and functional_blocks:
        layers = _derive_layers_from_blocks(functional_blocks)

    return ProjectConfig(
        name=name,
        system=name,
        output=OutputConfig(),
        layers=layers,
        functional_blocks=functional_blocks,
        metrics=metrics,
        root=root,
    )


def get_config(root: Path) -> ProjectConfig:
    """Load config from file if it exists, otherwise auto-discover.

    This is the recommended entry point — it always returns a valid config.
    When loading from YAML, auto-discovers sub_blocks for any block that
    doesn't already define them.

    Args:
        root: Project root directory.

    Returns:
        ProjectConfig (from file or auto-discovered).
    """
    config_path = root / CONFIG_FILENAME
    if config_path.exists():
        config = load_config(root)
        # Auto-discover sub_blocks for blocks that don't define them in YAML
        for block in config.functional_blocks:
            if not block.sub_blocks and block.dirs:
                block_path = root / block.dirs[0]
                if block_path.is_dir():
                    block.sub_blocks = _discover_sub_blocks(block_path, block.id, root)
        return config
    return discover_config(root)


def write_config(config: ProjectConfig, root: Path | None = None) -> Path:
    """Write a ProjectConfig to .architecture-model.yaml.

    Args:
        config: The configuration to write.
        root: Directory to write to. Defaults to config.root.

    Returns:
        Path to the written config file.
    """
    if root is None:
        root = config.root

    config_path = root / CONFIG_FILENAME
    data = config.to_dict()

    # Add auto-generation marker
    header = (
        "# Architecture Model Standard - Project Descriptor\n"
        "# Auto-generated by: architecture-model init\n"
        "# Edit freely - subsequent 'init' runs will not overwrite manual changes.\n\n"
    )

    yaml_content = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    config_path.write_text(header + yaml_content, encoding="utf-8")
    return config_path


# ---------------------------------------------------------------------------
# Auto-discovery heuristics
# ---------------------------------------------------------------------------

# Common layer patterns for Python web projects
_LAYER_HEURISTICS: list[tuple[str, list[str]]] = [
    ("web-layer", ["app/routers", "app/views", "app/api", "src/api", "api/"]),
    ("services-layer", ["app/services", "src/services", "services/"]),
    ("data-layer", ["app/models", "src/models", "models/", "alembic"]),
    ("pipeline-layer", ["scripts", "pipeline", "src/pipeline", "jobs/"]),
    ("scheduling-layer", ["app/tasks", "tasks/", "celery/"]),
]

# Common metric patterns
_METRIC_HEURISTICS: list[dict[str, Any]] = [
    {
        "label": "router",
        "paths": ["app/routers", "app/api", "src/api"],
        "pattern": "*.py",
        "exclude": ["__init__.py"],
    },
    {
        "label": "model",
        "paths": ["app/models", "src/models"],
        "pattern": "*.py",
        "exclude": ["__init__.py", "base.py"],
    },
    {
        "label": "migration",
        "paths": ["alembic/versions", "migrations"],
        "pattern": "*.py",
        "exclude": [],
    },
    {
        "label": "template",
        "paths": ["app/templates", "templates"],
        "pattern": "**/*.html",
        "exclude": [],
        "recursive": True,
    },
]


def _discover_layers(root: Path) -> list[LayerConfig]:
    """Discover architecture layers from directory structure."""
    layers: list[LayerConfig] = []

    for layer_id, candidate_dirs in _LAYER_HEURISTICS:
        found_dirs = [d for d in candidate_dirs if (root / d).is_dir()]
        if found_dirs:
            layers.append(LayerConfig(id=layer_id, dirs=found_dirs))

    return layers


def _discover_metrics(root: Path) -> list[MetricConfig]:
    """Discover countable metrics from directory structure."""
    metrics: list[MetricConfig] = []

    for heuristic in _METRIC_HEURISTICS:
        for path in heuristic["paths"]:
            if (root / path).is_dir():
                metrics.append(
                    MetricConfig(
                        label=heuristic["label"],
                        path=path,
                        pattern=heuristic["pattern"],
                        exclude=heuristic["exclude"],
                        recursive=heuristic.get("recursive", False),
                    )
                )
                break  # Use first match per label

    return metrics


# ---------------------------------------------------------------------------
# Sub-block auto-discovery
# ---------------------------------------------------------------------------


def _discover_sub_blocks(
    block_dir: Path,
    block_id: str,
    root: Path,
    depth: int = 0,
    max_depth: int = 3,
) -> list:
    """Discover sub-blocks from sub-directories within a block's directory.

    Only creates sub-blocks for directories that contain .py files.
    Recurses up to max_depth levels.
    """
    from .schema import SubBlockConfig

    if depth >= max_depth:
        return []

    sub_blocks = []
    sub_idx = 0

    try:
        children = sorted(block_dir.iterdir())
    except (PermissionError, OSError):
        return []

    for child in children:
        if not child.is_dir():
            continue
        if child.name.startswith(".") or child.name == "__pycache__":
            continue

        # Check if this directory has Python files
        py_files = list(child.glob("*.py"))
        if not py_files:
            continue

        sub_idx += 1
        # Use letter suffixes: F8.A, F8.B, etc. For deeper levels: F8.A.1, F8.A.2
        if depth == 0:
            sub_id = f"{block_id}.{chr(64 + sub_idx)}"  # A, B, C...
        else:
            sub_id = f"{block_id}.{sub_idx}"  # numeric for deeper levels

        # Get name from directory or __init__.py docstring
        name = child.name.replace("_", " ").title()
        init_file = child / "__init__.py"
        if init_file.exists():
            try:
                content = init_file.read_text(encoding="utf-8")
                # Extract module docstring
                import ast

                tree = ast.parse(content)
                if (
                    tree.body
                    and isinstance(tree.body[0], ast.Expr)
                    and isinstance(tree.body[0].value, ast.Constant)
                ):
                    docstring = tree.body[0].value.value
                    first_line = docstring.strip().split("\n")[0].strip()
                    if first_line and len(first_line) < 80:
                        name = first_line
            except Exception:
                pass

        rel_dir = str(child.relative_to(root))

        # Recurse into sub-directories
        nested = _discover_sub_blocks(child, sub_id, root, depth + 1, max_depth)

        sub_blocks.append(
            SubBlockConfig(
                id=sub_id,
                name=name,
                dirs=[rel_dir],
                files=[],
                description="",
                sub_blocks=nested,
            )
        )

    return sub_blocks


# ---------------------------------------------------------------------------
# Functional block auto-discovery
# ---------------------------------------------------------------------------


def _discover_functional_blocks(root: Path) -> list[FunctionalBlockConfig]:
    """Auto-discover functional blocks from source directory structure.

    Strategy:
    1. Find the "source root" — the package directory with Python modules.
    2. Each immediate subdirectory with .py files becomes an F-block.
    3. Names are derived from directory name and module docstrings.
    4. Files in the source root itself (not in subdirs) become a "Core" block.

    Falls back to top-level directory analysis if no clear package structure.
    """
    # Step 1: Find the source root (deepest package with subpackages)
    source_root = _find_source_root(root)
    if source_root is None:
        # No clear package structure — try top-level dirs
        return _fblocks_from_top_level_dirs(root)

    # Step 2: Enumerate subdirectories that contain Python code
    subdirs = _get_code_subdirectories(source_root)
    if not subdirs:
        return []

    # Step 3: Generate F-blocks from subdirectories
    blocks: list[FunctionalBlockConfig] = []
    rel_source = source_root.relative_to(root)

    for idx, subdir in enumerate(sorted(subdirs), start=1):
        block_id = f"F{idx}"
        rel_dir = str(subdir.relative_to(root))

        # Collect .py files in this subdir (non-recursive for files list)
        py_files = sorted(
            str(f.relative_to(root)) for f in subdir.rglob("*.py") if f.name != "__init__.py"
        )

        # Derive name from directory name
        dir_name = subdir.name.replace("_", " ").replace("-", " ").title()

        # Try to get description from __init__.py docstring
        description = _get_package_description(subdir)

        # Auto-discover sub-blocks from sub-directories
        sub_blocks = _discover_sub_blocks(subdir, block_id, root)

        blocks.append(
            FunctionalBlockConfig(
                id=block_id,
                name=dir_name,
                dirs=[rel_dir],
                files=py_files,
                description_source=description or f"auto-discovered from {rel_dir}/",
                sub_blocks=sub_blocks,
            )
        )

    return blocks


def _find_source_root(root: Path) -> Path | None:
    """Find the main source package directory.

    Checks common patterns:
    - src/<package>/  (src-layout)
    - <package>/  (flat layout, where <package> has __init__.py)
    - lib/<package>/
    """
    # src-layout: src/<something>/__init__.py with subdirectories
    src_dir = root / "src"
    if src_dir.is_dir():
        for child in src_dir.iterdir():
            if child.is_dir() and (child / "__init__.py").exists():
                # Check it has subdirectories with code
                if _get_code_subdirectories(child):
                    return child

    # Flat layout: look for a package dir at root level
    # (exclude common non-package dirs)
    _skip = {
        "tests",
        "test",
        "docs",
        "doc",
        "scripts",
        "bin",
        "output",
        "build",
        "dist",
        ".git",
        ".venv",
        "venv",
        "node_modules",
        "__pycache__",
        ".eggs",
        ".tox",
        "htmlcov",
        ".mypy_cache",
    }
    for child in sorted(root.iterdir()):
        if child.is_dir() and child.name not in _skip and not child.name.startswith("."):
            if (child / "__init__.py").exists() and _get_code_subdirectories(child):
                return child

    # lib-layout
    lib_dir = root / "lib"
    if lib_dir.is_dir():
        for child in lib_dir.iterdir():
            if child.is_dir() and (child / "__init__.py").exists():
                if _get_code_subdirectories(child):
                    return child

    return None


def _get_code_subdirectories(package_dir: Path) -> list[Path]:
    """Get immediate subdirectories that contain Python code (are subpackages)."""
    result = []
    for child in sorted(package_dir.iterdir()):
        if not child.is_dir() or child.name.startswith("_") or child.name.startswith("."):
            continue
        # Must have at least one .py file (directly or nested)
        py_files = list(child.rglob("*.py"))
        if py_files:
            result.append(child)
    return result


def _get_package_description(package_dir: Path) -> str:
    """Extract a short description from a package's __init__.py docstring."""
    init_file = package_dir / "__init__.py"
    if not init_file.exists():
        return ""

    content = init_file.read_text(encoding="utf-8", errors="ignore")
    # Simple docstring extraction (first triple-quoted string)
    for quote in ('"""', "'''"):
        if quote in content:
            start = content.index(quote) + 3
            end = content.find(quote, start)
            if end > start:
                doc = content[start:end].strip()
                # Return first line only
                first_line = doc.split("\n")[0].strip()
                if first_line:
                    return first_line
    return ""


def _fblocks_from_top_level_dirs(root: Path) -> list[FunctionalBlockConfig]:
    """Fallback: create F-blocks from top-level directories with Python files.

    Used when no clear package structure (src/ or flat package) is found.
    """
    _skip = {
        "tests",
        "test",
        "docs",
        "doc",
        "output",
        "build",
        "dist",
        ".git",
        ".venv",
        "venv",
        "node_modules",
        "__pycache__",
        ".eggs",
        ".tox",
        "htmlcov",
        ".mypy_cache",
        "alembic",
    }

    blocks: list[FunctionalBlockConfig] = []
    idx = 1

    for child in sorted(root.iterdir()):
        if not child.is_dir() or child.name in _skip or child.name.startswith("."):
            continue

        py_files = sorted(
            str(f.relative_to(root)) for f in child.rglob("*.py") if f.name != "__init__.py"
        )
        if not py_files:
            continue

        dir_name = child.name.replace("_", " ").replace("-", " ").title()
        description = _get_package_description(child) if (child / "__init__.py").exists() else ""

        # Auto-discover sub-blocks from sub-directories
        sub_blocks = _discover_sub_blocks(child, f"F{idx}", root)

        blocks.append(
            FunctionalBlockConfig(
                id=f"F{idx}",
                name=dir_name,
                dirs=[child.name],
                files=py_files,
                description_source=description or f"auto-discovered from {child.name}/",
                sub_blocks=sub_blocks,
            )
        )
        idx += 1

    return blocks


def _derive_layers_from_blocks(blocks: list[FunctionalBlockConfig]) -> list[LayerConfig]:
    """Derive layers from F-block directories when no heuristic layers found.

    Groups blocks into generic layers based on directory naming patterns.
    """
    layers: list[LayerConfig] = []
    all_dirs = [d for b in blocks for d in b.dirs]

    # For simple packages, create one layer per F-block dir
    for d in all_dirs:
        layer_id = d.split("/")[-1] + "-layer"
        layers.append(LayerConfig(id=layer_id, dirs=[d]))

    return layers
